name: uncertainpy_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiohappyeyeballs=2.4.0=py38haa95532_0
  - aiohttp=3.10.5=py38h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - aom=3.5.0=h63175ca_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - arrow=1.3.0=py38haa95532_0
  - asteval=1.0.6=pyhd8ed1ab_0
  - astroid=2.14.2=py38haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38haa95532_0
  - asyncssh=2.17.0=py38haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=24.2.0=py38haa95532_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - babel=2.11.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py38h2bbff1b_1
  - beautifulsoup4=4.12.3=py38haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=24.8.0=py38haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.5=hdccc3a2_0
  - boltons=23.0.0=py38haa95532_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py38hd3f51b4_8
  - bzip2=1.0.8=h2bbff1b_6
  - c-blosc2=2.12.0=h183a6f4_0
  - ca-certificates=2025.2.25=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.8.30=py38haa95532_0
  - cffi=1.17.0=py38h4cb3324_0
  - cfitsio=4.2.0=h9ebe7e4_0
  - chardet=4.0.0=py38haa95532_1003
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=py38haa95532_0
  - cloudpickle=3.0.0=py38haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=py38haa95532_0
  - conda=24.9.2=py38haa95532_0
  - conda-build=24.9.0=py38haa95532_0
  - conda-index=0.5.0=py38haa95532_0
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py38haa95532_0
  - conda-package-streaming=0.10.0=py38haa95532_0
  - contourpy=1.1.1=py38hb1fd069_1
  - cookiecutter=2.6.0=py38haa95532_0
  - cryptography=43.0.0=py38h89fc84f_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py38haa95532_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.9=pyhd8ed1ab_0
  - distro=1.9.0=py38haa95532_0
  - docstring-to-markdown=0.11=py38haa95532_0
  - docutils=0.18.1=py38haa95532_3
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py38haa95532_0
  - flake8=7.0.0=py38haa95532_0
  - fmt=10.2.1=h181d51b_0
  - fonttools=4.53.1=py38h4cb3324_0
  - freetype=2.12.1=hdaf720e_2
  - frozendict=2.4.2=py38h2bbff1b_0
  - frozenlist=1.4.0=py38h2bbff1b_0
  - future=0.18.3=py38haa95532_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h64bf75a_0
  - glib=2.82.2=h3d4babf_1
  - glib-tools=2.82.2=h4394cf3_1
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py38hd93224d_102
  - hdf5=1.14.3=nompi_hb2c4d47_109
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.2=h63175ca_0
  - idna=3.10=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py38h29c013e_2
  - imageio=2.36.0=pyh12aca89_1
  - imagesize=1.4.1=py38haa95532_0
  - importlib-metadata=7.0.1=py38haa95532_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - inflection=0.5.1=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.29.5=py38haa95532_0
  - ipython=8.12.2=py38haa95532_0
  - isort=5.13.2=py38haa95532_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py38haa95532_0
  - jellyfish=1.0.1=py38h36a85e1_0
  - jinja2=3.1.4=py38haa95532_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsonpatch=1.33=py38haa95532_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38haa95532_0
  - jsonschema-specifications=2023.7.1=py38haa95532_0
  - jupyter_client=8.6.0=py38haa95532_0
  - jupyter_core=5.7.2=py38haa95532_0
  - jupyterlab_pygments=0.2.2=py38haa95532_0
  - jxrlib=1.1=hcfcfb64_3
  - keyring=24.3.1=py38haa95532_0
  - kiwisolver=1.4.5=py38hb1fd069_1
  - krb5=1.21.3=hdf4eb48_0
  - lazy-loader=0.4=pyhd8ed1ab_1
  - lazy-object-proxy=1.10.0=py38h2bbff1b_0
  - lazy_loader=0.4=pyhd8ed1ab_1
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libaec=1.1.3=h63175ca_0
  - libarchive=3.7.7=h88ece9c_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libavif=0.11.1=ha7b97ba_2
  - libblas=3.9.0=20_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=20_win64_mkl
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.11.1=h88aaa65_0
  - libdeflate=1.18=hcfcfb64_0
  - libffi=3.4.4=hd77b12b_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.82.2=h7025463_1
  - libhwloc=2.11.2=default_hc8275d1_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.1.5.1=hcfcfb64_1
  - liblapack=3.9.0=20_win64_mkl
  - liblief=0.12.3=hd77b12b_0
  - liblzma=5.6.4=h2466b09_0
  - liblzma-devel=5.6.4=h2466b09_0
  - libmamba=1.5.8=h3f09ed1_0
  - libmambapy=1.5.8=py38h9d63bcc_0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.46=had7236b_0
  - libsodium=1.0.18=h62dcd97_0
  - libsolv=0.7.30=hbb528cf_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libsqlite=3.48.0=h67fdade_1
  - libssh2=1.11.1=he619c9f_0
  - libtiff=4.5.1=h6c8260b_1
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.13.5=he286e8c_1
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - lmfit=1.3.2=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=he774522_2
  - m2-msys2-runtime=2.5.0.17080.65c939c=3
  - m2-patch=2.7.5=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=2.2.0=py38haa95532_1
  - markupsafe=2.1.3=py38h2bbff1b_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdurl=0.1.0=py38haa95532_0
  - menuinst=2.2.0=py38h5da7b33_0
  - mistune=2.0.4=py38haa95532_0
  - mkl=2023.2.0=h6a75c08_50497
  - mkl-service=2.4.0=py38h2bbff1b_1
  - more-itertools=10.3.0=py38haa95532_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py38h2bbff1b_0
  - multiprocess=0.70.16=py38h91455d4_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=py38haa95532_0
  - nbclient=0.8.0=py38haa95532_0
  - nbconvert=7.16.4=py38haa95532_0
  - nbformat=5.10.4=py38haa95532_0
  - nest-asyncio=1.6.0=py38haa95532_0
  - networkx=3.1=pyhd8ed1ab_0
  - numpy=1.24.4=py38h1d91fd2_0
  - numpydoc=1.5.0=py38haa95532_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.5.0=ha4e3fda_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.0.3=py38hf08cf0d_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathos=0.3.2=pyhd8ed1ab_1
  - pathspec=0.10.3=py38haa95532_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.0=py38ha7eb54a_0
  - pip=24.2=py38haa95532_0
  - pkginfo=1.10.0=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.0.0=py38haa95532_1
  - ply=3.11=py38_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pox=0.3.5=pyhd8ed1ab_0
  - ppft=1.7.6.9=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=py38haa95532_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-lief=0.12.3=py38hd77b12b_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycodestyle=2.11.1=py38haa95532_0
  - pycosat=0.6.6=py38h2bbff1b_1
  - pycparser=2.22=pyhd8ed1ab_0
  - pydocstyle=6.3.0=py38haa95532_0
  - pyflakes=3.2.0=py38haa95532_0
  - pygithub=2.4.0=py38haa95532_0
  - pygments=2.15.1=py38haa95532_1
  - pyjwt=2.8.0=py38haa95532_0
  - pylint=2.16.2=py38haa95532_0
  - pylint-venv=3.0.3=py38haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py38h8cc25b3_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pyqtwebengine=5.15.10=py38hd77b12b_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-libarchive-c=5.1=pyhd3eb1b0_0
  - python-lsp-black=2.0.0=py38haa95532_0
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.10.0=py38haa95532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytoolconfig=1.2.6=py38haa95532_0
  - pytz=2024.2=pyhd8ed1ab_0
  - pyuca=1.2=py38haa95532_1
  - pywavelets=1.4.1=py38he7056a7_1
  - pywin32=305=py38h2bbff1b_0
  - pywin32-ctypes=0.2.2=py38haa95532_0
  - pyyaml=6.0.2=py38h827c3e9_0
  - pyzmq=25.1.2=py38hd77b12b_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py38haa95532_0
  - qt-main=5.15.8=he5a7383_16
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtawesome=1.3.1=py38haa95532_0
  - qtconsole=5.5.1=py38haa95532_0
  - qtpy=2.4.1=py38haa95532_0
  - referencing=0.30.2=py38haa95532_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.3=pyhd8ed1ab_0
  - rich=13.7.1=py38haa95532_0
  - rope=1.12.0=py38haa95532_0
  - rpds-py=0.10.6=py38h062c2fa_0
  - rtree=1.0.1=py38h2eaa2aa_0
  - ruamel.yaml=0.18.6=py38h827c3e9_0
  - ruamel.yaml.clib=0.2.8=py38h827c3e9_0
  - scikit-image=0.21.0=py38hd3f51b4_0
  - scikit-learn=1.3.2=py38h4f736e5_2
  - scipy=1.10.1=py38hdcfc7df_1
  - setuptools=75.1.0=py38haa95532_0
  - setuptools-scm=8.1.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py38haa95532_0
  - sphinx=5.0.2=py38haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.5.1=py38haa95532_4
  - spyder-kernels=2.5.0=py38haa95532_0
  - spyder-vim=0.1.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.1=py38he7056a7_0
  - superqt=0.6.7=py38h9909e9c_0
  - tbb=2021.13.0=h62715c5_1
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2023.7.10=pyhd8ed1ab_0
  - tinycss2=1.2.1=py38haa95532_0
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=py38haa95532_0
  - tomlkit=0.13.2=py38haa95532_0
  - tornado=6.4.1=py38h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=py38haa95532_0
  - typing-extensions=4.11.0=py38haa95532_0
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - ujson=5.10.0=py38h5da7b33_0
  - uncertainties=3.2.2=pyhd8ed1ab_1
  - unicodedata2=15.1.0=py38h91455d4_0
  - unidecode=1.3.8=py38haa95532_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.42=haa95532_3
  - vc14_runtime=14.42.34433=h6356254_24
  - vs2015_runtime=14.42.34433=hfef2bbc_24
  - watchdog=4.0.1=py38haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - whatthepatch=1.0.2=py38haa95532_0
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - wrapt=1.14.1=py38h2bbff1b_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xvfbwrapper=0.2.9=pyhd8ed1ab_1005
  - xz=5.6.4=h208afaa_0
  - xz-tools=5.6.4=h2466b09_0
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.8.0=hd77b12b_1
  - yapf=0.40.2=py38haa95532_0
  - yarl=1.11.0=py38h827c3e9_0
  - zeromq=4.3.5=hd77b12b_0
  - zfp=1.0.1=he0c23c2_2
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstandard=0.23.0=py38hf92978b_0
  - zstd=1.5.6=h0ea2cb4_0
